const LOADING_MSGS = [
    "Loading cocktail recipes...",
    "Mixing up some drinks...",
    "Shaking things up...",
    "Chilling your glass...",
    "Squeezing fresh citrus...",
    "Muddling mint...",
    "Blending frozen delights...",
    "Pouring a tall one...",
    "Frosting the rim...",
    "Gathering garnishes...",
    "Aerate the wine...",
    "Infusing flavors...",
    "Brewing coffee cocktails...",
    "Serving up tiki drinks...",
    "Preparing aperitifs...",
    "Sequencing shooter recipes...",
    "Layering liquors...",
    "Fizzling some fizz...",
    "Whipping up some foam...",
    "Uncorking the bubbly...",
    "Juicing fresh fruits...",
    "Stirring up some classics...",
    "Calculating cocktail ratios...",
    "Preparing punch bowls...",
    "Crafting mocktails...",
    "Decanting the wine...",
    "Floating some fun...",
    "Chilling the shaker...",
    "Building up the bar...",
    "Assembling your ingredients...",
    "Spritzing the spritz...",
    "Aging the whiskey...",
    "Twisting the twist...",
    "Bittersweet symphony...",
    "Pairing the perfect cocktails...",
    "Distilling the essence...",
    "Mixing up a storm...",
    "Concocting some magic...",
    "Finding your signature cocktail...",
    "Serving up some sass...",
    "Muddling, shaking, and stirring...",
    "Brewing the perfect blend...",
    "Tapping the keg...",
    "Crushing ice...",
    "Slicing and dicing...",
    "Mixing the perfect martini...",
    "Loading your happy hour...",
    "Livening up the party...",
    "Fine-tuning the flavors...",
    "Getting ready to unwind...",
    "Raising the bar..."
]

var BASE_INGREDIENTS = [
    "lemon juice",
    "vodka",
    "gin",
    "lime juice",
    "luxardo maraschino liqueur",
    "angostura bitters",
    "king's ginger liqueur",
    "orange juice",
    "sugar",
    "junipero gin",
    "no.3 london dry gin",
    "simple syrup",
    "lemon",
    "fresh lemon juice",
    "egg white",
    "h by hine",
    "light rum",
    "ice",
    "grenadine",
    "pineapple juice",
    "triple sec",
    "dry vermouth",
    "fresh lime juice",
    "lime",
    "amaretto",
    "milk",
    "water",
    "pink pigeon rum",
    "orange bitters",
    "cranberry juice",
    "lemon peel",
    "brandy",
    "luxardo sangue morlacco cherry liqueur",
    "luxardo bitter bianco",
    "luxardo amaretto di saschira",
    "powdered sugar",
    "kahlua",
    "coffee",
    "luxardo amaro abano",
    "tequila",
    "mezcal",
    "karlsson's gold vodka",
    "orange",
    "sweet vermouth",
    "luxardo apricot liqueur",
    "bailey's irish cream",
    "luxardo triplum (triple sec)",
    "soda water",
    "bourbon",
    "club soda",
];